### ISSUE TITLE
T2w SPACE increase FOV?

### ISSUE THREAD

**Issue by thomshaw92** [spine-generic/protocols#13]
Hi @jcohenadad and team,
I have seen in some of the SCT docs that the T2w has a much larger FOV than the default protocol (we are running on Siemens Prisma). 
Are there recommendations for how far down the spine this protocol can be extended without running into e.g. distortion issues? I'd like to acquire spine down to above the conus. Any parameter choices would be appreciated! 
Thanks 
![Screenshot_20241116-114550](https://github.com/user-attachments/assets/3c8e2cc6-3e91-4616-964e-72c20b2b0b7c)

**Comment by jcohenadad** [comment]
Hi @thomshaw92,

I'd say that above 40cm FOV, you might want to consider acquiring two FOV that slightly overlap and then stitch them either online (eg using Syngo's SPINE tool if you are on Siemens and have the licence) or using offline tools, like [`sct_image -stitch`](https://spinalcordtoolbox.com/stable/user_section/command-line/sct_image.html).

**Comment by thomshaw92** [comment]
Thanks! Appreciate it. Assuming SCT can label to above conus with the one stitched image then?

**Comment by jcohenadad** [comment]
> Assuming SCT can label to above conus with the one stitched image then?

Yes it can, depending what you mean by 'label' (ie vertebral or spinal)
